---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

  - name: Join the Worker nodes with the master.
    become: yes
    become_method: sudo
    become_user: root
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not

  - debug:
      msg: "{{ joined_or_not.stdout }}"

 
